---
# file: roles/mail/tasks/mail_debian.yml

- name: Install msmtp
  action: apt pkg={{ item }} state=latest
  with_items:
    - msmtp
    - msmtp-mta
    - ca-certificates

- name: Mail | Adjust /etc/msmtprc
  action: template src=msmtprc.j2 dest=/etc/msmtprc

- name: Remove exim4-base and exim4-config
  apt: pkg={{ item }} state=absent
  with_items:
    - exim4-base
    - exim4-config

- name: Sending a testmail to {{ mail.from_address }}
  shell: cat /etc/hostname | msmtp -s test {{ mail.from_address }}
  when: ansible_distribution in [ 'Ubuntu' ]

- name: Sending a testmail to {{ mail.from_address }}
  shell: cat /etc/hostname | mail -s test {{ mail.from_address }}
  when: ansible_distribution in [ 'Debian' ]